version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # The entrypoint and command are now defined within the Dockerfile
    volumes:
      - ./:/var/www/html/
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Use the service name 'db' for inter-container communication
      - DB_HOST=db
      - DB_NAME=network_monitor
      - DB_USER=user
      - DB_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - ADMIN_PASSWORD=password
      # SMTP Environment Variables for Email Notifications (Update these with your actual SMTP details)
      - SMTP_HOST=smtp.example.com
      - SMTP_USER=your_email@example.com
      - SMTP_PASS=your_email_password
      - SMTP_SECURE=tls # or ssl
      - SMTP_PORT=587 # or 465 for SSL
      - SMTP_FROM_EMAIL=your_email@example.com
      - SMTP_FROM_NAME="AMPNM Notifier"
      - NOTIFICATION_EMAIL=admin@example.com # Default recipient for test emails
    restart: unless-stopped
    ports:
      - "2266:80" # Expose app on port 2266 of the host

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: network_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      # Expose the database port to the host for external tools if needed
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: