version: '3.8'

services:
  app:
    build: .
    ports:
      - "2266:80"
    volumes:
      - ./:/var/www/html/
    environment:
      # This will be automatically injected with your Supabase DB connection string
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
    restart: unless-stopped