version: '3.8'

services:
  app:
    build: .
    ports:
      - "2266:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=network_monitor
      - DB_USER=user
      - DB_PASSWORD=password
    restart: unless-stopped

  db:
    image: mysql:8.0
    # Add command to ensure compatible authentication
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: network_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    # Use a more robust healthcheck that runs a query
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "show databases;"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: