version: '3.8'

services:
  network-monitor-react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: network-monitor-react