version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "-c", "chmod +x /var/www/html/docker-entrypoint.sh && /var/www/html/docker-entrypoint.sh"]
    volumes:
      - ./:/var/www/html/
    depends_on:
      db:
        condition: service_healthy
      sales_licensing_app: # Main app now depends on the licensing app
        condition: service_healthy
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=network_monitor
      - DB_USER=user
      - DB_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - ADMIN_PASSWORD=password
      # New: License Management Environment Variables for the main app
      # This URL points to the license validation API of the separate sales_licensing_app service
      - LICENSE_API_URL=http://sales_licensing_app:3377/api/v1/validate-license
      - LICENSE_KEY=YOUR_PRODUCT_LICENSE_KEY_HERE # Replace with the actual license key for this deployment
    ports:
      - "2266:2266" # Main app will now run on port 2266
    restart: unless-stopped
    # network_mode: "host" # Removed host mode as explicit port mapping is used

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: network_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  sales_licensing_app:
    build:
      context: ./new-php-app # Points to the new directory
      dockerfile: Dockerfile
    ports:
      - "3377:80" # Map external port 3377 to internal Apache port 80
    environment:
      # Supabase credentials for the new app (replace with your actual Supabase project details)
      - SUPABASE_URL=https://eauhhlfldgzxcwslqemu.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdWhobGZsZGd6eGN3c2xxZW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDg5NTgsImV4cCI6MjA3MDI4NDk1OH0.4JA8LlaE3cwUDSwbzO7NsWX09KZL75UQ7W2a3EN4XMA
    volumes:
      - ./new-php-app:/var/www/html # Mount your new PHP app code here
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/v1/validate-license || exit 1"] # Health check for the API endpoint on internal port 80
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data: